server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/hiramcheca/Microservicios-Tutorial.git
          default-label: config-server
          search-paths: config-data
  application:
    name: config-service